"""HTML export functionality."""

from typing import Dict, Any, List, Optional
from datetime import datetime
from pathlib import Path
from jinja2 import Environment, FileSystemLoader, select_autoescape

from nyx.core.logger import get_logger

logger = get_logger(__name__)


class HTMLExporter:
    """Export OSINT data to HTML format."""

    DEFAULT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            border-bottom: 3px solid #007bff;
            padding-bottom: 10px;
        }
        h2 {
            color: #555;
            margin-top: 30px;
        }
        .metadata {
            background: #f8f9fa;
            padding: 15px;
            border-left: 4px solid #007bff;
            margin-bottom: 20px;
        }
        .profile {
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 15px;
            border-radius: 4px;
        }
        .profile h3 {
            margin-top: 0;
            color: #007bff;
        }
        .attribute {
            display: flex;
            margin: 8px 0;
        }
        .attribute-key {
            font-weight: bold;
            min-width: 150px;
            color: #555;
        }
        .attribute-value {
            color: #333;
        }
        .tag {
            display: inline-block;
            background: #007bff;
            color: white;
            padding: 3px 10px;
            border-radius: 3px;
            margin-right: 5px;
            font-size: 12px;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #777;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #007bff;
            color: white;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        .redacted {
            background: #000;
            color: #000;
            user-select: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ title }}</h1>

        <div class="metadata">
            <div class="attribute">
                <span class="attribute-key">Generated:</span>
                <span class="attribute-value">{{ generated_at }}</span>
            </div>
            {% if description %}
            <div class="attribute">
                <span class="attribute-key">Description:</span>
                <span class="attribute-value">{{ description }}</span>
            </div>
            {% endif %}
        </div>

        {% if profiles %}
        <h2>Profiles ({{ profiles|length }})</h2>
        {% for profile in profiles %}
        <div class="profile">
            <h3>{{ profile.platform }}</h3>
            {% for key, value in profile.items() %}
            {% if key != 'platform' and value %}
            <div class="attribute">
                <span class="attribute-key">{{ key|title }}:</span>
                <span class="attribute-value">{{ value }}</span>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endfor %}
        {% endif %}

        {% if data %}
        <h2>Additional Data</h2>
        <table>
            <thead>
                <tr>
                    {% for key in data[0].keys() %}
                    <th>{{ key|title }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                <tr>
                    {% for value in item.values() %}
                    <td>{{ value }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}

        <div class="footer">
            Generated by Nyx OSINT Platform v0.1.0<br>
            {{ generated_at }}
        </div>
    </div>
</body>
</html>
"""

    def __init__(self, template_dir: Optional[str] = None) -> None:
        """Initialize HTML exporter.

        Args:
            template_dir: Directory containing Jinja2 templates
        """
        self.template_dir = Path(template_dir) if template_dir else None

        if self.template_dir and self.template_dir.exists():
            self.env = Environment(
                loader=FileSystemLoader(str(self.template_dir)),
                autoescape=select_autoescape(["html", "xml"]),
            )
        else:
            self.env = None

    def export(
        self,
        data: Dict[str, Any],
        output_path: str,
        title: str = "OSINT Investigation Report",
        description: str = "",
        template_name: Optional[str] = None,
        redact_fields: Optional[List[str]] = None,
    ) -> None:
        """Export data to HTML.

        Args:
            data: Data to export
            output_path: Output file path
            title: Report title
            description: Report description
            template_name: Custom template name
            redact_fields: Fields to redact
        """
        try:
            if redact_fields:
                data = self._redact_fields(data, redact_fields)

            context = {
                "title": title,
                "description": description,
                "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "profiles": data.get("profiles", []),
                "data": data.get("data", []),
            }

            if self.env and template_name:
                template = self.env.get_template(template_name)
                html = template.render(**context)
            else:
                from jinja2 import Template

                template = Template(self.DEFAULT_TEMPLATE)
                html = template.render(**context)

            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(html)

            logger.info(f"Exported HTML report to {output_path}")

        except Exception as e:
            logger.error(f"Failed to export HTML: {e}")
            raise

    def _redact_fields(self, data: Dict[str, Any], fields: List[str]) -> Dict[str, Any]:
        """Redact specified fields.

        Args:
            data: Data to redact
            fields: Fields to redact

        Returns:
            Redacted data
        """
        import copy

        redacted = copy.deepcopy(data)

        def redact_recursive(obj: Any) -> Any:
            if isinstance(obj, dict):
                for key in list(obj.keys()):
                    if key in fields:
                        obj[key] = "[REDACTED]"
                    else:
                        obj[key] = redact_recursive(obj[key])
            elif isinstance(obj, list):
                return [redact_recursive(item) for item in obj]
            return obj

        return redact_recursive(redacted)
